service: godblessyou

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: provided.al2  # Amazon Linux 2 사용
  region: us-east-1
  ecr:
    images:
      appimage:
        uri: 471112984004.dkr.ecr.us-east-1.amazonaws.com/godblessyou:latest

functions:
  app:
    image:
      name: appimage
    timeout: 120
    memorySize: 2048
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - app/**
    - handler.py
    - config/**
    - node_modules/**
    - .git/**
    - tests/**
